name: Update Wiki

on:
  push:
    paths:
      - 'wiki/**'
    branches:
      - main
jobs:
  update-wiki:
    runs-on: ubuntu-latest
    name: Update wiki
    permissions:
      pages: write
    steps:
    - uses: OrlovM/Wiki-Action@v1
      with:
        path: 'wiki'
        token: ${{ secrets.GITHUB_TOKEN }}
